#!/usr/bin/env bash

# Backup the original /etc/hosts file
sudo cp /etc/hosts /etc/hosts.bak

# Add entries to /etc/hosts
sudo sed -i '/127.0.0.1 localhost/d' /etc/hosts
echo "127.0.0.2 localhost" | sudo tee -a /etc/hosts
echo "8.8.8.8 facebook.com" | sudo tee -a /etc/hosts